//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayMonitoringSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blotterreport
    {
        public int Blotternumber { get; set; }
        public string ResidentFirstName { get; set; }
        public string ResidentMiddleName { get; set; }
        public string ResidentLastName { get; set; }
        public string Incidentlocation { get; set; }
        public string Incidenttype { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Datereported { get; set; }
        public string DateIncident { get; set; }
    }
}
