//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayMonitoringSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentRegister
    {
        public int ID { get; set; }
        public string ResidentFirstName { get; set; }
        public string ResidentMiddleName { get; set; }
        public string ResidentLastName { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public string Status { get; set; }
        public string Occupation { get; set; }
        public string Nationality { get; set; }
        public string Birthdate { get; set; }
        public string PlaceofBirth { get; set; }
        public int ContactNumber { get; set; }
    }
}
